INSERT INTO `entladungs` (`name`) VALUES
('GR KL Vitfrisch'),
('Van Wylick Köln'),
('GR Lager EDEKA'),
('GR Lager KL'),
('Andretta'),
('GR Lager FOF'),
('GR Lager'),
('Kärcher'),
('GR Lager Deininger'),
('Kueste Thieshope'),
('Kueste Ostrau'),
('Kueste vW Köln'),
('Vit'),
('FHF'),
('GR FHF'),
('vdHamm'),
('GR vW Olching'),
('GR Lager (Terra)'),
('HUB '),
('FHF Andretta'),
('GR vdHamm'),
('Sinn'),
('HUB (L0612)'),
('GR VIT'),
('GR Lager Amazon'),
('Deininger'),
('Köhra'),
('HUB (L0213)'),
('GR Lager Wasgau'),
('HUB (L0511)'),
('HUB (L0611)'),
('HUB (L0112)'),
('GR Lager Terra'),
('HUB (L0212)');